/* 
 * HitBTC API
 *
 * Create API keys in your profile https://hitbtc.com/settings/api-keys and use public API key as username and secret as password to authorize. 
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ErrorError
    /// </summary>
    [DataContract]
    public partial class ErrorError :  IEquatable<ErrorError>, IValidatableObject
    {
        /// <summary>
        /// Defines Message
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MessageEnum
        {
            
            /// <summary>
            /// Enum InternalServerError for value: Internal Server Error
            /// </summary>
            [EnumMember(Value = "Internal Server Error")]
            InternalServerError = 1,
            
            /// <summary>
            /// Enum GatewayTimeout for value: Gateway Timeout
            /// </summary>
            [EnumMember(Value = "Gateway Timeout")]
            GatewayTimeout = 2,
            
            /// <summary>
            /// Enum ServiceUnavailable for value: Service Unavailable
            /// </summary>
            [EnumMember(Value = "Service Unavailable")]
            ServiceUnavailable = 3,
            
            /// <summary>
            /// Enum Symbolnotfound for value: Symbol not found
            /// </summary>
            [EnumMember(Value = "Symbol not found")]
            Symbolnotfound = 4,
            
            /// <summary>
            /// Enum Authorisationrequired for value: Authorisation required
            /// </summary>
            [EnumMember(Value = "Authorisation required")]
            Authorisationrequired = 5,
            
            /// <summary>
            /// Enum Authorisationfailed for value: Authorisation failed
            /// </summary>
            [EnumMember(Value = "Authorisation failed")]
            Authorisationfailed = 6,
            
            /// <summary>
            /// Enum Validationerror for value: Validation error
            /// </summary>
            [EnumMember(Value = "Validation error")]
            Validationerror = 7,
            
            /// <summary>
            /// Enum Insufficientfunds for value: Insufficient funds
            /// </summary>
            [EnumMember(Value = "Insufficient funds")]
            Insufficientfunds = 8
        }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public MessageEnum Message { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorError" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ErrorError() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorError" /> class.
        /// </summary>
        /// <param name="code">code (required).</param>
        /// <param name="message">message (required).</param>
        /// <param name="description">description.</param>
        public ErrorError(int? code = default(int?), MessageEnum message = default(MessageEnum), string description = default(string))
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new InvalidDataException("code is a required property for ErrorError and cannot be null");
            }
            else
            {
                this.Code = code;
            }
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new InvalidDataException("message is a required property for ErrorError and cannot be null");
            }
            else
            {
                this.Message = message;
            }
            this.Description = description;
        }
        
        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public int? Code { get; set; }


        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ErrorError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ErrorError);
        }

        /// <summary>
        /// Returns true if ErrorError instances are equal
        /// </summary>
        /// <param name="input">Instance of ErrorError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ErrorError input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
