/* 
 * HitBTC API
 *
 * Create API keys in your profile https://hitbtc.com/settings/api-keys and use public API key as username and secret as password to authorize. 
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Address
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AddressTests
    {
        // TODO uncomment below to declare an instance variable for Address
        //private Address instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Address
            //instance = new Address();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Address
        /// </summary>
        [Test]
        public void AddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Address
            //Assert.IsInstanceOfType<Address> (instance, "variable 'instance' is a Address");
        }


        /// <summary>
        /// Test the property '_Address'
        /// </summary>
        [Test]
        public void _AddressTest()
        {
            // TODO unit test for the property '_Address'
        }
        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Test]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

    }

}
