/* 
 * HitBTC API
 *
 * Create API keys in your profile https://hitbtc.com/settings/api-keys and use public API key as username and secret as password to authorize. 
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Currency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CurrencyTests
    {
        // TODO uncomment below to declare an instance variable for Currency
        //private Currency instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Currency
            //instance = new Currency();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Currency
        /// </summary>
        [Test]
        public void CurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Currency
            //Assert.IsInstanceOfType<Currency> (instance, "variable 'instance' is a Currency");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Crypto'
        /// </summary>
        [Test]
        public void CryptoTest()
        {
            // TODO unit test for the property 'Crypto'
        }
        /// <summary>
        /// Test the property 'PayinEnabled'
        /// </summary>
        [Test]
        public void PayinEnabledTest()
        {
            // TODO unit test for the property 'PayinEnabled'
        }
        /// <summary>
        /// Test the property 'PayinPaymentId'
        /// </summary>
        [Test]
        public void PayinPaymentIdTest()
        {
            // TODO unit test for the property 'PayinPaymentId'
        }
        /// <summary>
        /// Test the property 'PayinConfirmations'
        /// </summary>
        [Test]
        public void PayinConfirmationsTest()
        {
            // TODO unit test for the property 'PayinConfirmations'
        }
        /// <summary>
        /// Test the property 'PayoutEnabled'
        /// </summary>
        [Test]
        public void PayoutEnabledTest()
        {
            // TODO unit test for the property 'PayoutEnabled'
        }
        /// <summary>
        /// Test the property 'PayoutFee'
        /// </summary>
        [Test]
        public void PayoutFeeTest()
        {
            // TODO unit test for the property 'PayoutFee'
        }
        /// <summary>
        /// Test the property 'PayoutIsPaymentId'
        /// </summary>
        [Test]
        public void PayoutIsPaymentIdTest()
        {
            // TODO unit test for the property 'PayoutIsPaymentId'
        }
        /// <summary>
        /// Test the property 'Delisted'
        /// </summary>
        [Test]
        public void DelistedTest()
        {
            // TODO unit test for the property 'Delisted'
        }
        /// <summary>
        /// Test the property 'TransferEnabled'
        /// </summary>
        [Test]
        public void TransferEnabledTest()
        {
            // TODO unit test for the property 'TransferEnabled'
        }

    }

}
