/* 
 * HitBTC API
 *
 * Create API keys in your profile https://hitbtc.com/settings/api-keys and use public API key as username and secret as password to authorize. 
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Orderbook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderbookTests
    {
        // TODO uncomment below to declare an instance variable for Orderbook
        //private Orderbook instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Orderbook
            //instance = new Orderbook();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Orderbook
        /// </summary>
        [Test]
        public void OrderbookInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Orderbook
            //Assert.IsInstanceOfType<Orderbook> (instance, "variable 'instance' is a Orderbook");
        }


        /// <summary>
        /// Test the property 'Ask'
        /// </summary>
        [Test]
        public void AskTest()
        {
            // TODO unit test for the property 'Ask'
        }
        /// <summary>
        /// Test the property 'Bid'
        /// </summary>
        [Test]
        public void BidTest()
        {
            // TODO unit test for the property 'Bid'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

    }

}
