/* 
 * HitBTC API
 *
 * Create API keys in your profile https://hitbtc.com/settings/api-keys and use public API key as username and secret as password to authorize. 
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Symbol
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SymbolTests
    {
        // TODO uncomment below to declare an instance variable for Symbol
        //private Symbol instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Symbol
            //instance = new Symbol();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Symbol
        /// </summary>
        [Test]
        public void SymbolInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Symbol
            //Assert.IsInstanceOfType<Symbol> (instance, "variable 'instance' is a Symbol");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'BaseCurrency'
        /// </summary>
        [Test]
        public void BaseCurrencyTest()
        {
            // TODO unit test for the property 'BaseCurrency'
        }
        /// <summary>
        /// Test the property 'QuoteCurrency'
        /// </summary>
        [Test]
        public void QuoteCurrencyTest()
        {
            // TODO unit test for the property 'QuoteCurrency'
        }
        /// <summary>
        /// Test the property 'QuantityIncrement'
        /// </summary>
        [Test]
        public void QuantityIncrementTest()
        {
            // TODO unit test for the property 'QuantityIncrement'
        }
        /// <summary>
        /// Test the property 'TickSize'
        /// </summary>
        [Test]
        public void TickSizeTest()
        {
            // TODO unit test for the property 'TickSize'
        }
        /// <summary>
        /// Test the property 'TakeLiquidityRate'
        /// </summary>
        [Test]
        public void TakeLiquidityRateTest()
        {
            // TODO unit test for the property 'TakeLiquidityRate'
        }
        /// <summary>
        /// Test the property 'ProvideLiquidityRate'
        /// </summary>
        [Test]
        public void ProvideLiquidityRateTest()
        {
            // TODO unit test for the property 'ProvideLiquidityRate'
        }
        /// <summary>
        /// Test the property 'FeeCurrency'
        /// </summary>
        [Test]
        public void FeeCurrencyTest()
        {
            // TODO unit test for the property 'FeeCurrency'
        }

    }

}
