/* 
 * HitBTC API
 *
 * Create API keys in your profile https://hitbtc.com/settings/api-keys and use public API key as username and secret as password to authorize. 
 *
 * OpenAPI spec version: 2.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TradingFee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TradingFeeTests
    {
        // TODO uncomment below to declare an instance variable for TradingFee
        //private TradingFee instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TradingFee
            //instance = new TradingFee();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TradingFee
        /// </summary>
        [Test]
        public void TradingFeeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TradingFee
            //Assert.IsInstanceOfType<TradingFee> (instance, "variable 'instance' is a TradingFee");
        }


        /// <summary>
        /// Test the property 'TakeLiquidityRate'
        /// </summary>
        [Test]
        public void TakeLiquidityRateTest()
        {
            // TODO unit test for the property 'TakeLiquidityRate'
        }
        /// <summary>
        /// Test the property 'ProvideLiquidityRate'
        /// </summary>
        [Test]
        public void ProvideLiquidityRateTest()
        {
            // TODO unit test for the property 'ProvideLiquidityRate'
        }

    }

}
